# Generated by Django 4.1.7 on 2023-02-15 16:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_headline', models.CharField(max_length=100)),
                ('about_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='blog.jpg', upload_to='blog_pictures')),
            ],
        ),
        migrations.CreateModel(
            name='CommentReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(max_length=250)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_description', models.TextField()),
                ('company_phonenumber', models.PositiveBigIntegerField()),
                ('company_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_description', models.TextField()),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_subject', models.CharField(max_length=100)),
                ('contact_message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactAgentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='contact.jpg', upload_to='contact_pictures')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PropertyAmenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity_one', models.CharField(blank=True, max_length=100, null=True)),
                ('amenity_two', models.CharField(blank=True, max_length=100, null=True)),
                ('amenity_three', models.CharField(blank=True, max_length=100, null=True)),
                ('amenity_four', models.CharField(blank=True, max_length=100, null=True)),
                ('amenity_five', models.CharField(blank=True, max_length=100, null=True)),
                ('amenity_six', models.CharField(blank=True, max_length=100, null=True)),
                ('amenity_seven', models.CharField(blank=True, max_length=100, null=True)),
                ('amenity_eight', models.CharField(blank=True, max_length=100, null=True)),
                ('amenity_nine', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='property.jpg', upload_to='property_pictures')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_headline', models.CharField(max_length=100)),
                ('service_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TestimonialImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='testimonials.jpg', upload_to='testimonials_pictures')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('testimonal_description', models.TextField()),
                ('image', models.ManyToManyField(to='realestateapp.testimonialimage')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=100)),
                ('property_location', models.TextField()),
                ('video', models.FileField(blank=True, null=True, upload_to='videos_uploaded', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('property_price', models.FloatField()),
                ('property_type', models.CharField(choices=[('2 Bedroom Apartment', '2 Bedroom Apartment'), ('3 Bedroom Apartment', '3 Bedroom Apartment'), ('4 Bedroom Apartment', '4 Bedroom Apartment'), ('Duplex', 'Duplex'), ('Terrace', 'Terrace'), ('Penthouse ', 'Penthouse')], max_length=100)),
                ('property_status', models.CharField(choices=[('Sale', 'Sale'), ('Rent', 'Rent')], max_length=100)),
                ('property_squaremeter', models.PositiveIntegerField()),
                ('beds', models.PositiveIntegerField()),
                ('baths', models.PositiveIntegerField()),
                ('garage', models.PositiveIntegerField()),
                ('floorplan_image', models.ImageField(blank=True, null=True, upload_to='images_uploaded')),
                ('property_image', models.ManyToManyField(to='realestateapp.propertyimage')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_headline', models.CharField(max_length=100)),
                ('blog_content', models.TextField()),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('blog_category', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('blog_image', models.ManyToManyField(to='realestateapp.blogimage')),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=100)),
                ('agent_description', models.TextField()),
                ('agent_mobilenumber', models.PositiveBigIntegerField()),
                ('agent_email', models.EmailField(max_length=254)),
                ('agent_image', models.ManyToManyField(to='realestateapp.contactagentimage')),
            ],
        ),
    ]
