# Generated by Django 4.1.7 on 2023-02-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestateapp', '0002_property_house_number_property_property_zipcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'Properties'},
        ),
        migrations.RemoveField(
            model_name='propertyamenities',
            name='amenity_eight',
        ),
        migrations.RemoveField(
            model_name='propertyamenities',
            name='amenity_five',
        ),
        migrations.RemoveField(
            model_name='propertyamenities',
            name='amenity_four',
        ),
        migrations.RemoveField(
            model_name='propertyamenities',
            name='amenity_nine',
        ),
        migrations.RemoveField(
            model_name='propertyamenities',
            name='amenity_one',
        ),
        migrations.RemoveField(
            model_name='propertyamenities',
            name='amenity_seven',
        ),
        migrations.RemoveField(
            model_name='propertyamenities',
            name='amenity_six',
        ),
        migrations.RemoveField(
            model_name='propertyamenities',
            name='amenity_three',
        ),
        migrations.RemoveField(
            model_name='propertyamenities',
            name='amenity_two',
        ),
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.ManyToManyField(blank=True, null=True, to='realestateapp.propertyamenities'),
        ),
        migrations.AddField(
            model_name='propertyamenities',
            name='amenities',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
