# Generated by Django 4.1.7 on 2023-02-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestateapp', '0003_alter_property_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
