# Generated by Django 4.1.7 on 2023-02-20 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestateapp', '0004_property_property_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyamenities',
            name='amenities',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
