# Generated by Django 4.1.7 on 2023-02-20 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestateapp', '0005_alter_propertyamenities_amenities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='amenities',
            field=models.ManyToManyField(to='realestateapp.propertyamenities'),
        ),
        migrations.AlterField(
            model_name='propertyamenities',
            name='amenities',
            field=models.CharField(max_length=200),
        ),
    ]
