# Generated by Django 4.1.7 on 2023-02-20 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestateapp', '0006_alter_property_amenities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimage',
            name='image',
            field=models.ImageField(default='blog.jpg', upload_to='album_pictures'),
        ),
        migrations.AlterField(
            model_name='contactagentimage',
            name='image',
            field=models.ImageField(default='contact.jpg', upload_to='album_pictures'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(default='property.jpg', upload_to='album_pictures'),
        ),
        migrations.AlterField(
            model_name='testimonialimage',
            name='image',
            field=models.ImageField(default='testimonials.jpg', upload_to='album_pictures'),
        ),
    ]
