# Generated by Django 4.1.7 on 2023-02-21 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestateapp', '0007_alter_blogimage_image_alter_contactagentimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimage',
            name='image',
            field=models.ImageField(default='realestate.jpg', upload_to='album_pictures'),
        ),
        migrations.AlterField(
            model_name='contactagentimage',
            name='image',
            field=models.ImageField(default='realestate.jpg', upload_to='album_pictures'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(default='realestate.jpg', upload_to='album_pictures'),
        ),
        migrations.AlterField(
            model_name='testimonialimage',
            name='image',
            field=models.ImageField(default='realestate.jpg', upload_to='album_pictures'),
        ),
    ]
