# Generated by Django 4.1.7 on 2023-02-21 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestateapp', '0008_alter_blogimage_image_alter_contactagentimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='comapany_location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogimage',
            name='image',
            field=models.ImageField(default='blog.jpg', upload_to='album_pictures'),
        ),
        migrations.AlterField(
            model_name='contactagentimage',
            name='image',
            field=models.ImageField(default='contact.jpg', upload_to='album_pictures'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(default='property.jpg', upload_to='album_pictures'),
        ),
        migrations.AlterField(
            model_name='testimonialimage',
            name='image',
            field=models.ImageField(default='testimonials.jpg', upload_to='album_pictures'),
        ),
    ]
