# Generated by Django 4.1.7 on 2023-02-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestateapp', '0010_rename_comapany_location_companydetails_company_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'About'},
        ),
        migrations.AlterModelOptions(
            name='commentreply',
            options={'verbose_name_plural': 'Comment replies'},
        ),
        migrations.AlterModelOptions(
            name='companydetails',
            options={'verbose_name_plural': 'Company details'},
        ),
        migrations.AlterModelOptions(
            name='propertyamenities',
            options={'verbose_name_plural': 'Property amenities'},
        ),
        migrations.AlterField(
            model_name='blogimage',
            name='image',
            field=models.ImageField(blank=True, default='blog.jpg', null=True, upload_to='album_pictures'),
        ),
        migrations.AlterField(
            model_name='contactagentimage',
            name='image',
            field=models.ImageField(blank=True, default='contact.jpg', null=True, upload_to='album_pictures'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(blank=True, default='property.jpg', null=True, upload_to='album_pictures'),
        ),
        migrations.AlterField(
            model_name='testimonialimage',
            name='image',
            field=models.ImageField(blank=True, default='testimonials.jpg', null=True, upload_to='album_pictures'),
        ),
    ]
