# Generated by Django 4.1.7 on 2023-02-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestateapp', '0011_alter_about_options_alter_commentreply_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contact_description',
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_image',
            field=models.ManyToManyField(blank=True, null=True, to='realestateapp.blogimage'),
        ),
    ]
